# Enable all linters except the deprecated and annoying ones
linters:
  enable-all: true
  disable:
    # Deprecated
    - nosnakecase
    - exhaustivestruct
    - varcheck
    - interfacer
    - structcheck
    - maligned
    - scopelint
    - ifshort
    - golint
    - deadcode
    # Not relevant for me
    - depguard
    # Causes false positives
    # - gocritic # Does not recognize errors.Is
    # Just annoying
    - gomnd
    - godox
    - wrapcheck
